# -*- coding: utf-8 -*-
"""ch04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuF0OeVwV8XAwy07GtDjSZ2USnVwYh7h
"""

# 어제 내용 복습
튜플은 변하지 않는것들 - 튜플을 지정하거나 할 일은 많지 않다.
딕셔너리 - 키는 해시가능하고 변경 불가능한 자료형만 가능
딕셔너리를 만드는 방법은 여러가지. 함수로 만들수도 있고 튜플로 묶어서 만들수도 있고
set - 변경 가능한 집합

#반복문 - for
```ptython
for<target> in <object seq>:
  <수행할 문장1>
  <수행할 문장2>
else: # 쓸 수도 있고, 안쓰는 일이 많긴 하다
  <수행한 문장3>
````
- for문은 임의의 시퀀스의 항목들을 그 시퀀스에 있는 순서대로 이터레이션 한다.

for i in [1,2,3,4]:
  print(i)
  print("===끝===")

treehit = 0
while treehit < 10 :
  treehit = treehit +1
  print(f"나무를 {treehit}번 찍었습니다.")
  if treehit == 10:
    print("나무 넘어갑니다.")

coffee = 10
money = 300
while money:
  print("돈을 받았으니 커피를 줍니다.")
  coffee = coffee-1
  print(f"남은 양의 커피는 {coffee} 입니다.")
  if not coffee:
    print("커피가 다 떨어졌습니다. 판매를 중단합니다. ")
    break

a = 0
while a < 10:
  a=a+1
  if a%2 ==0:
      continue
  print(a)

for i in ["소","양","돼지","닭"]:
  print(i)
  print("끝")

for i in range(10):
  print(f"{i}번 반복되고 있습니다.")

for i in range(0,16,3): #start = 0 stop = 16 step = 3
  print(f"{i}번 반복되고 있습니다.")

acc=0
for i in range(1,11):
  print(f"old_acc : {acc}")
  acc = acc+i
  print(f"new_acc : {acc}")
  print("="*10)
print(f"결과는 {acc}입니다.")

"""2를 10번 곱해봐라

"""

x_num = 1
for i in range(1,11):
  x_num = x_num*2
  print(f"현재 숫자는 {x_num} 입니다.")
  print("="*10)
print(f"결과는 {x_num}입니다.")

a=[]
for i in range(1,11):
  a = a + [i]
  print(a)
print(f"결과는 {a} 입니다.")

a = [0 for i in range(10)]
for i in range(1,11):
  a[i-1] = i
  print(a)

a=[]
for i in range(1,11):
  a.append(i)
  print(a)
print(f"결과는 {a} 입니다.")

list_name = ["가","나","다","라"]
list_math = [11,23,89,90]
list_kor = [22,34,13,67]

list_score = list(zip(list_name, list_math, list_kor))

for k, i, j in list_score:
  print(f"이름 : {k}")
  print(f"수학점수 : {i}")
  print(f"국어점수 : {j}")

score = [15, 60, 80, 65, 72, 80]
name = ["가","나","다","라","마","바"]
grade = []
# 70점 미만의 학생은 불합격, 이상의 학생은 합격이 출력되도록 작성하세요.
# 1번 학생은 15점으로 불합격
for i in score :
  if i >= 70:
    grade.append("합격")
  else :
    grade.append("불합격")
list_num = list(zip(name, score,grade))
for k, i, j in list_num:
  print(f"{k}학생은 {i}점으로 {j}.")

for i, j in enumerate(score, start=1):
  if j >= 70:
    print(f"{i}번 학생은 {j}으로 합격")
  else :
    print(f"{i}번 학생은 {j}으로 불합격")

#구구단을 출력하도록
#몇단을 계산하실건가요? 2

dan = int(input("몇 단을 계산하실 건가요? : "))
for i in range(1,10):
  print(f"{dan}x{i}={dan*i}")

"""# list comprehension
- list 내부에 조건식을 넣을 수 있다.
```
list_3=[]
list  i in range(2,8):
list_3.append(i)
```
"""

list_2=[2,3,4,5,6,7]

list_3=[]
for i in range(1000):
  list_3.append(i)

list_4=[i for i in range(1000)]

list_5=[i*2 for i in range(100)]

list_7 = [i for i in range(1,5) if i%2==0]

list_7

"""#for문 계속"""

# continue
# 조건을 강제로 반복하게 만든다.
marks = [90, 25, 67, 45, 80]
number = 0
for mark in marks :
  number = number+1
  if mark < 60 :
    continue
  print(f"{number}번 학생 축하합니다. 합격입니다.")

a = [11, 22, 33]
for i in a:
  print(f"i : {i}")
  print("===")
  if i == 11:
    print(i)
    pass
  print("2")

# 1단부터 9단까지 한번에 출력되도록 작성해보세요
for j in range(1,10):
  dan = j
  print("="*5,f"{dan}단","="*5)
  for i in range(1,10):
    print(f"{dan}x{i}={dan*i}")

seasons = ["봄","여름","가을","겨울"]
for season1 in seasons:
  if season1 == "겨울":
    print(f"아 {season1} 진짜 추워 죽겠다.")
  else:
    print(f"현재 계절은 {season1}이 아닙니다.")

for i in range(1,6):
  print("★"*i)

for i in range(1,6):
  for j in range(1,i+1):
    print("★",end="")
  print("")

for i in range(5,0,-1):
  print("★"*i)

for i in range(1,6):
  print("☆"*(5-i),"★"*i,sep="")

for i in range(1,6):
  print(" "*(5-i),"★"*i,)

# 문자 자체를 정렬
for i in range(1,6):
  print(("★"*i).center(10))

for i in range(6):
  print("{:>5}".format("★"*i))

"""#while 문의 기본형
```
while<condition>:
  <문장1>
  <문장2>
else:
  <문장3>
```
"""

i = 1
while i <10:
  print(i)
  i=i+1

count_init = 0
acc_init = 0
while count_init < 10:
  count_init+=1
  acc_init +=count_init

a=[11,22,33]
for i in a:
  print(f"i: {i}")
  print("1")
  if i ==11:
    print(i)
    pass
    print("3")
  print("2")

apart=[[1001, 1002, 1003, 1004, 1005, 1006],[2001, 2002, 2003, 2004, 2005, 2006], [3001, 3002, 3003, 3004, 3005, 3006], [4001, 4002, 4003, 4004, 4005, 4006]]
refusal = [1001,2006,3005,4004]
for i in range(len(apart)):
  for j in range(len(apart[0])):
    if apart[i][j] in refusal:
      pass
    else:
      print(f"신문 배달 : {apart[i][j]}")

i = 0
j = 0
while i < len(apart) :
  while j < len(apart[0]):
    if apart[i][j] in refusal:
      pass
    else:
      print(f"신문 배달 : {apart[i][j]}")
    j += 1
  i += 1

coke = 101
money = int(input("현금을 입력하세요 : "))
while True:
  count = int(input("coke를 몇 개 뽑으시겠습니까? : "))
  if coke == 0:
    print("이제 coke가 더 없습니다.")
    break
  elif money < 1000:
    print("이제 현금이 없습니다.")
    break
  elif (count*1000) > money:
    print("그만큼 coke를 뽑을 돈이 없습니다.")
  else:
    coke -= count
    money -= count*1000
    print(f"coke {count}개 출력\n",f"거스름돈 {money}를 받으세요\n",f"coke가 {coke}개 남았습니다.\n",end="")
    pass

import random
ran_num = random.randint(1,100)
number = int(input("숫자를 맞춰봐\n 몇일까?\n"))
while True:
  if number == ran_num:
    print("정답입니다!")
    break
  else :
    if number > ran_num:
      print("숫자가 큽니다.")
    else :
      print("숫자가 작습니다.")
    number = int(input("다시 맞춰봐\n"))
    continue

import random
win_num = 0
lose_num = 0
tie_num = 0

for i in range (1,11):
  ran_num = random.randint(1,3)
  srp = input("가위 바위, 보 : ")
  if srp == "가위":
    srp_num = 1
  elif srp == "바위":
    srp_num = 2
  elif srp == "보":
    srp_num = 3
  else :
    print("가위, 바위, 보 중에서만 골라야지!")
    continue
  if srp_num == ran_num:
    print("비겼다!")
    tie_num += 1
  elif ((srp_num == 1) & (ran_num == 3)) | ((srp_num == 2) & (ran_num == 1)) | ((srp_num == 3) & (ran_num == 2)):
    print("이겼다!")
    win_num += 1
  else :
    print("졌다...")
    lose_num += 1
print(f"승 : {win_num} \n패 : {lose_num} \n비김 : {tie_num}")

from ast import Pass
import random
win_num = 0
lose_num = 0
tie_num = 0
i = 0

while i <10:
  ran_num = random.randint(1,3)
  srp = input("가위 바위, 보 : ")
  if srp == "가위":
    srp_num = 1
  elif srp == "바위":
    srp_num = 2
  elif srp == "보":
    srp_num = 3
  else :
    print("가위, 바위, 보 중에서만 골라야지!")
    continue
  i += 1
  if srp_num == ran_num:
    print("비겼다!")
    tie_num += 1
  elif ((srp_num == 1) & (ran_num == 3)) | ((srp_num == 2) & (ran_num == 1)) | ((srp_num == 3) & (ran_num == 2)):
    print("이겼다!")
    win_num += 1
  else :
    print("졌다...")
    lose_num += 1
print(f"승 : {win_num} \n패 : {lose_num} \n비김 : {tie_num}")

